version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Install phase complete"
  pre_build:
    commands:
      - echo "Pre-build phase complete"
  build:
    commands:
      - echo "Build phase complete"
  post_build:
    commands:
      - echo "Post-build phase complete"

artifacts:
  files:
    - '**/*'
