custombucket = "destinationtxt"
table = "intellipaat"
databasehost = "database-1.cleokuouukfq.us-east-1.rds.amazonaws.com"
duser = "intel"
dpass = "intel123"
s3database = "intellipaat"
kapp = "http://3.228.220.21/"
